spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: library

  jackson:
    time-zone: America/Sao_Paulo


  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.spi.PersistenceContext: DEBUG
server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /library

management:
  endpoints:
    web:
      exposure:
        include: heapdump, health
    enabled-by-default: true
  endpoint:
    heapdump:
      enabled: true

app:
  name: "@project.name@"
  version: "@project.version@"
  description: "@project.description@"